### PR TITLE
Bug fix: Fix IllegalArgumentException for enums

### LINKED ISSUE #26: Exceptions
Task for the Course Project
(Exceptions)

Make changes to the project to avoid Exceptions when using enums according to the video “Exceptions. Project Development.”

Additional Task:
To better understand the learned material, it is recommended to independently analyze the approaches to avoid IllegalArgumentException when using the valueOf(...) method with a non-existent enum value. Refactor the code to apply a consistent approach throughout the entire project.

After completing the tasks and verifying their functionality, merge all the changes into the main branch.

### PR DESCRIPTION
**Pull request by oleksandr-sydorskyi**
## Explanation of Project Changes
- Enums have replaced all listings in the program.
- Changes were made to the project to avoid Exceptions when using enums.
- Methods were created for parsing strings into enums.
- Methods were created to print a list of enums.
The goal was also to ensure that adding a new value to the enum would not require any code changes.

### CODE REVIEW

**Comment by KaterynaMir** [comment]
It looks like you have successfully achieved your goal )
The code is fine and can be merged as is to the main. The only remark I have is about the usage of try-catch approach in the fromString method of the Size enum.  In other enums you have used another approach. The task was "Refactor the code to apply a consistent approach throughout the entire project." So may be it is worth to refactor the Size enum in line with the others?

**Review by KaterynaMir — APPROVED** [review]

**Comment by oleksandr-sydorskyi** [comment]
When I asked if additional checks should be done in setters, our mentor responded that it is better not to include any checks in setters, as this is considered business logic.

This has changed my understanding of encapsulation. I need more information on this topic. For now, I’m removing all checks from my setters.

**Comment by vini607** [comment]
good work! :)

**Review by vini607 — COMMENTED** [review]
it's ready for merge

**Review by vini607 — COMMENTED** [review]
good work!

**Pull request merged**
