### PR TITLE
Req 12 code improvements

### PR DESCRIPTION
**Pull request by oleksandr-sydorskyi**
I found all the tips interesting and worth implementing. 
- I've introduced a new class StringUtils for common string operations.
- The sortDogsbyField method was adjusted to sortPetsByField to handle sorting for all types of pets.
- In the StringUtils class, the capitalizeFirstLetter method now capitalizes the first letters in double names.
- I'll remove the enum value in the next iteration as it's no longer necessary.

### CODE REVIEW

**Comment by KaterynaMir** [comment]
Good work! It was great idea to add the StringUtils class. The method sortPetsByField provides a wide variety of sorting options.

A few notes: 

1. Sorting by age field could result  in exception if age is equal to "UNKNOWN".
2.  I would recommend to explicitly set "cat" type in Cat constructor with parameters (and correspondingly "dog" type in Dog constructor with parameters)
3. The capitalizePart method could be included into the capitalizeFirstLetter method: 
```
public static String capitalizeFirstLetter(String input) {
        String[] parts = input.split("-");
        input = Character.toUpperCase(parts[0].charAt(0)) + parts[0].substring(1).toLowerCase();
        return parts.length == 1 ? input : input + "-" + capitalizeFirstLetter(parts[1]);
    }
```

**Comment by oleksandr-sydorskyi** [comment]
Good tips, keep it up!

- Modified the `sortPetsByField` method to handle cases where age equals "UNKNOWN".
- Pet types are now set during the creation of a pet.
- Combined the `capitalizeFirstLetter` method with the `capitalizePart` method into a single method.

**Comment by KaterynaMir** [comment]
Wow, may be it's time to merge to the main? ;)

It's hard for me sometimes to stop improving. And sometimes it's not for the best ). So I leave below my concerns, and you feel free to decide whether they are needed:

1. The name pattern doesn't limit the number of hyphens, so there could be more than one hyphen in input. And in this case function capitalizeFirstLetter will lose the third and other parts of the name/surname. 
This can be overriden, but it complicates the code:

 ```
public static String capitalizeFirstLetter(String input) {
        String[] parts = input.split("-");
        String capitalizedInput = "";
        for (String part : parts) {
            part = Character.toUpperCase(part.charAt(0)) + part.substring(1).toLowerCase();
            capitalizedInput = capitalizedInput + part + "-";
        }
        return capitalizedInput.substring(0,capitalizedInput.length()-1);
    }
```
2. The UNKNOWN(0) instance of enum Size in Dog class probably should be also put to the first place.

**Review by vini607 — COMMENTED** [review]
good work :)

**Comment by oleksandr-sydorskyi** [comment]
I found a convenient method for joining elements of an array (or any iterable) into a single string using a specified delimiter. It is a String.join(String delimiter, String[] elements).
```java
    public static String capitalizeFirstLetter(String input) {
        String[] parts = input.split("-");
        for (int i = 0; i < parts.length; i++) {
            parts[i] = Character.toUpperCase(parts[i].charAt(0)) + parts[i].substring(1).toLowerCase();
        }
        return String.join("-", parts);
    }
```

**Comment by KaterynaMir** [comment]
Well done! The String.join method fits very well to this task.

**Review by KaterynaMir — APPROVED** [review]
The code is well-written and can be pushed to the main branch

**Pull request merged**
