### PR TITLE
REQ-10: code improvements

### LINKED ISSUE #14: Task-7 Make changes to the project, use enums, and implement the ability to sort dogs by size using an anonymous inner class
Task for the course project

(Anonymous classes)

Make changes to the project, use enums, and implement the ability to sort dogs by size using an anonymous inner class according to the video "Anonymous classes: project development, sorting implementation."

Extra task:

For better understanding of the learned material, it is suggested to independently add a field named healthState to the Pet class, using an enum, which indicates the current health state of the animal.

It would also be appropriate to implement sorting of animals based on this field (healthState) so that veterinarians can provide assistance to animals in the correct order.

### PR DESCRIPTION
**Pull request by oleksandr-sydorskyi**
### Pet Class Enhancement:
- Added the healthState field using an enum and implemented sorting of animals based on this field.
### Refactored Method in ClientService:
- Replaced isNameValid and isEmailValid methods with a more general isValidInput method.
### Refactored Method Signature in PetService:
- Updated the registerNewPet method to accept a Client object as a parameter, enabling direct interaction with client data.
### ClientService Modifications:
- The registerNewClient method underwent significant changes. Email validation was removed, and validation logic was moved to the buildClient method.
- The buildClient method now directly handles client creation and input validation, eliminating duplicate code.
### PetService Modifications:
- The registerNewPet method now directly interacts with the client's pet and sets its owner name.
- The buildPet method now directly handles pet creation and input validation, removing duplicate code.

### CODE REVIEW

**Comment by KaterynaMir** [comment]
A great work has been done! New important features have been added: the ability to sort pets on their health state is of vital importance.

I like the idea of moving input validation to the setters of Pet/Dog classes.
The refactoring of the ClientService class makes code more readable and easy to understand. 
Overall the changes made to the code look reasonable and functional.

There some minor improvements that I would recommend:
1. I think that the healthState field should be added also to the equals and hashCode methods of the Pet class.
2.  In the Sandbox it would be nice to add output of what type of sorting has been done before outputting the sorted fields of array.

I have doubts whether it is worth to transfer the client to the PetService. What if one client has several pets? Probably, it can be overcome. Anyway right now the code is working and it's up to the author's choice.

**Comment by oleksandr-sydorskyi** [comment]
### Review Comments:
1. **Adding `healthState` to `equals` and `hashCode` in `Pet` class:**
   - Good suggestion! Including `healthState` in `equals` and `hashCode` ensures pets are identified uniquely considering their health state.

2. **Adding output of sorting type in `Sandbox`:**
   - Excellent idea! Providing output indicating the type of sorting being performed in `Sandbox` enhances clarity and user understanding of the sorting process.

3. **Considering handling pet registration within the context of the client in `PetService`:**
   - It's a valid concern. Handling multiple pets for a single client within `PetService` ensures better organization and modularity. So, I left it for future enhancements.

**Comment by KaterynaMir** [comment]
Good work! I've nothing to add ;) The branch is ready to be merged to main.

**Review by vini607 — COMMENTED** [review]
All good! :)

**Pull request merged**
